---
provisioner:
  name: salt_solo
  salt_bootstrap_options: '-M -X stable 2016.3'
  salt_pillar_root: '/srv/salt/sp/pillar/'

  formula: sp
  state_top:
    base:
      '*':
        - sp.nginx
        - test.state.fixtures.nginx

  dependencies:
    - name: test/state/fixtures
      path: "."


platforms:
  - name: debian-8


suites:
  - name: docker
    driver:
      name: docker
      use_sudo: true
